language: cpp

os: linux

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          packages:
            - gcc-6
            - g++-6
            - cmake
            - clang-9
      env: CXX=g++-6 CC=gcc-6
    - os: osx
      osx_image: xcode11.3
      compiler: clang
      addons:
        homebrew:
          packages:
            - cmake
            - llvm@9
          update: true

install:
  - echo ${PATH}
  - echo ${CXX}
  - ${CXX} --version
  - cmake --version

branches:
  only:
    - master

script: ./build.sh ~/kaleidoscope
